/' Arquivo com diagrama de classe principal do projeto.
Para visualizar o diagrama instale o plugin do eclipse, ver instrucões em: http://plantuml.com/eclipse '/

@startuml
skinparam defaultFontName Monospace
skinparam ClassBackgroundColor<<View>> LightCyan
skinparam ClassBackgroundColor<<Enum>> WhiteSmoke
skinparam nodesep 200 
skinparam ranksep 100
' top to bottom direction
' left to right direction

package "br.jus.tre_pa.sof.domain" <<Frame>> {

	class OrcamentoAutorizado {
		- id: Long {id}
		- exercicio: Long
		- disponibilidadeUaEm: LocalDateTime
		- inicioVigenciaEm: LocalDateTime
		- fimVigenciaEm: LocalDateTime
		- processoSei: String
		-- tagged values --
		<b>@table.name</b>: ORCAMENTO_AUTORIZADO
	}

	class AcaoOrcamentaria {
		- id: Long {id}
		- nome: String
		- dotacaoFixada: BigDecimal
		-- tagged values --
		<b>@table.name</b>: ACAO_ORCAMENTARIA
	}

	class Unidade {
		- id: Long {id}
		- nome: String
		- tipo: UnidadeType
		- sigla: String
		- deprecatedAt: LocalDateTime
		-- tagged values --
		<b>@table.name</b>: UNIDADE
	}

	class GrupoDespesa {
		- id: Long {id}
		- codigo: Long
		- nome: String
		-- tagged values --
		<b>@table.name</b>: GRUPO_DESPESA
	}

	note right of GrupoDespesa 
		Investimento
		Custeio
		Capacitação
	end note

	class Ptres {
		- id: Long {id}
		- codigo: Long
		- nome: String
		-- tagged values --
		<b>@table.name</b>: PTRES
	}

	class DespesaAgregada {
		- id: Long {id}
		- codigo: Long
		- nome: String
		- descricao: String
		-- tagged values --
		<b>@table.name</b>: DESPESA_AGREGADA
	}

	class PlanoInterno {
		- id: Long {id}
		- nome: String
		-- tagged values --
		<b>@table.name</b>: PLANO_INTERNO
	}

	class Elemento {
		- id: Long {id}
		- codigo: string
		-- tagged values --
		<b>@table.name</b>: ELEMENTO
	}

	class ItemElemento {
		- id: Long {id}
		-- tagged values --
		<b>@table.name</b>: ITEM_ELEMENTO
	}

	class OperacaoOrcamentaria {
		- id: Long {id}
		- tipo: OperacaoOrcamentariaType
		- oficioTse: String
		- documentoSiaf: String
		- eventoSei: String
		- registradaSiafEm: LocalDateTime
		- valor: BigDecimal
		- observacao: String[2048]
		-- tagged values --
		<b>@table.name</b>: OP_ORCAMENTARIA
	}


	class SolicitacaoEmpenho {
		- id: Long {id}
		- descricao: String[2048]
		- processoSei: String {notnull}
		- eventoSei: String
		- status: String[2048]
		- solicitadoPor: String
		- solicitadoEm: LocalDateTime
		-- tagged values --
		<b>@table.name</b>: SOLIC_EMPENHO
	}

	class ItemSolicitacaoEmpenho {
		- id: Long {id}
		- valor: BigDecimal
		- solicitadoEm: LocalDateTime
		-- tagged values --
		<b>@table.name</b>: ITEM_SOLIC_EMPENHO
	}

	class ItemSolicitacaoEmpenhoType {
		- id: Long {id}
		- descricao: String
		- valorObrigatorio: boolean
		- notaEmpenhoAssociadoObrigatorio: boolean
		- justificativaObrigatoria: boolean
		- fatorMutiplicador: Integer[1]
		-- tagged values --
		<b>@table.name</b>: ITEM_SOLIC_EMPENHO_TYPE
	}


	class PreEmpenho {
		- id: Long {id}
		- numeroSiaf: String
		- tipo: PreEmpenhoType
		- valor: BigDecimal
		- emissaoSiafEm: LocalDateTime
		- registradoSiafEm: LocalDateTime
		- registradiPor: String
		-- tagged values --
		<b>@table.name</b>: PRE_EMPENHO

	}

	class NotaEmpenho {
		- id: Long {id}
		- numeroSiaf: String
		- especie: NotaEmpenhoEspecieType
		- dataEmissaoSiafEm: LocalDateTime
		- emitidoSiafPor: String
		- subItem: string
		- valor: BigDecimal
		- criadoEm: LocalDateTime
		- criadoPor: LocalDateTime
		- status: StatusNotaEmpenhoType
		-- tagged values --
		<b>@table.name</b>: NOTA_EMPENHO
	}

	class ItemAcaoOrcamentaria {
		- id: Long {id}
		-- tagged values --
		<b>@table.name</b>: ITEM_ACAO_ORCAMENTARIA
	}

	class ItemDespesaAgregada {
		- id: Long {id}
		-- tagged values --
		<b>@table.name</b>: ITEM_DESPESA_AGREGADA
	}

	class ItemPlanoInterno {
		- id: Long {id}
		-- tagged values --
		<b>@table.name</b>: ITEM_PLANO_INTERNO
	}


}

package "br.jus.tre_pa.sof.domain.enums" <<Frame>>{

	' enum SolicitacaoEmpenhoType {
		'     EMISSAO_NOTA_EMPENHO
		'     REFORCO_NOTA_EMPENHO
		'     ANULACAO_NOTA_EMPENHO
		' 	  REPACTUACAO_NOTA_EMPENHO
		' 	  REAJUSTE_NOTA_EMPENHO
		'  	  REVERSAO_PRE_EMPENHO

		'
	'}

	enum PreEmpenhoType<<Enum>> {
		EMISSAO_DE_EMPENHO
		EMISSAO_DE_REFORCO
		REVERSAO_DO_PRE_EMPENHO
		EMISSAO_REPACTUACAO
		EMISSAO_REAJUSTE
	}
	

	enum NotaEmpenhoEspecieType<<Enum>>  {
		EMISSAO
		REFORCO
		ANULACAO
	}

	enum OperacaoOrcamentariaType<<Enum>>  {
		SUPLEMENTACAO
		REMANEJAMENTO
		CONTIGENCIAMENTO
		DESCONTIGENCIAMENTO
	}



	enum StatusSolicitacaoEmpenhoType<<Enum>>  {
		INICIADO
		PRE_EMPENHO_GERADO
		EMPENHO_GERADO
		CANCELADO
	}

	enum StatusPreEmpenhoType<<Enum>>  {
		GERADA
		EMPENHO_GERADO
		CANCELADO
	}

	enum StatusNotaEmpenhoType<<Enum>>  {
		GERADO
		RESTOS_A_PAGAR
	}

	enum UnidadeType<<Enum>>  {
    		MACRO_UNIDADE
    		UGR
    }

}


package "br.jus.tre_pa.sof.domain.views" <<Frame>>{
	class VwOrcamento<<View>> {
		- id: Long {id}
		- orcamentoAutorizadoId:Long
		- acaoOrcamentariaId:Long
		- ptresId:Long
		- grupoDespesaId:Long
		- despesaAgregadaId: Long
		- planoInternoId: Long
		- elementoId: Long
		- ugrId: Long
		- macroUnidadeId: Long
		- contingenciamento: BigDecimal
		- suplementacao: BigDecimal
		- remanejamento: BigDecimal
		- dotacaoAtualizada: BigDecimal
		- disponivelSolicitacao: BigDecimal
		- preEmpenho: BigDecimal
		- disponivelPreEmpenho: BigDecimal
		- notaEmpenho: BigDecimal
		- disponivelNotaEmpenho: BigDecimal
		- disponivel: BigDecimal
	}
}

OrcamentoAutorizado "1" <-down-> "1..*" ItemAcaoOrcamentaria: possui > 
ItemAcaoOrcamentaria "1..*" -right-> "1" AcaoOrcamentaria
ItemAcaoOrcamentaria "1" -down-> "0..*" ItemDespesaAgregada: possui >
ItemDespesaAgregada "1..*" -up-> "1" DespesaAgregada: possui >
ItemDespesaAgregada "1" <-down-> "0..*" ItemPlanoInterno: possui >
ItemPlanoInterno  -right-> "1" PlanoInterno: possui > 
ItemPlanoInterno "1" <-down-> "0..*" ItemElemento: possui >
ItemElemento "1..*" <-up-> "1" Elemento: possui >
ItemElemento "1" <-down-> "1..*" ItemSolicitacaoEmpenho
ItemElemento "1" <-down-> "0..*" PreEmpenho
ItemElemento "1" <-down-> "0..*" OperacaoOrcamentaria: < possui 
ItemElemento "1" <-left-> "0..*" NotaEmpenho
ItemElemento "1" -up-> "1..*" Unidade: pertence >
ItemElemento "1" -up-> "1..*" OrcamentoAutorizado: pertence >
ItemSolicitacaoEmpenho "0..*" <-right-> "0..1" PreEmpenho: referencia >
note on link
	reversão
end note
ItemSolicitacaoEmpenho "0..1" <-right-> "0..*" PreEmpenho: < gera 
ItemSolicitacaoEmpenho "0..*" <-down-> "1" ItemSolicitacaoEmpenhoType: possui >
ItemSolicitacaoEmpenho "0..*" -down-> "1"  NotaEmpenho: referencia >
note on link
	anulação ou reforço
end note
ItemSolicitacaoEmpenho "1" -down-> "0..*"  NotaEmpenho: < gera            '    
PreEmpenho "0..1 \n preEmpenhoReferenciado" <-- "0..* \n preEmpenhosSubordinados" PreEmpenho: possui >
PreEmpenho "0..*" <-down->  "0..*" NotaEmpenho: possui >
NotaEmpenho "1 \n notasEmpenhosSuperior" <-right-> "0..* \n notasEmpenhosSubordinados" NotaEmpenho: possui >
DespesaAgregada "1" <-down-> "0..*" Ptres: possui >
DespesaAgregada "1" <-down-> "0..*" GrupoDespesa: possui >
SolicitacaoEmpenho "1" <-down-> "0..*" ItemSolicitacaoEmpenho: possui >
Unidade "1" <-left-> "0..*" SolicitacaoEmpenho: faz >
Unidade "1" <-up- ItemAcaoOrcamentaria: possui > 
Unidade "1..* \n unidadesSubordinadasResponsavel" <--> "1 \n unidadeSuperiorResponsavel" Unidade: possui > 
OperacaoOrcamentaria "0..1 \n operacaoOrcamentariaOrigem"  -- "0..* \n operacoesOrcamentariasDestino"  OperacaoOrcamentaria: operacoesOrcamentariaAssociadas >

@enduml
